project:
  type: default

title: "Comparing Econometric and Machine Learning Approaches to Forecasting Indiaâ€™s CPI Inflation: An Evaluation of ARIMAX and XGBoost Models"

format:
  pdf:
    figwidth: 12
    figheight: 6
    papersize: a4
    tbl-colwidths: auto
    geometry:
      - margin=15mm
    metadata:
      header-includes: |
        \usepackage{fvextra}
        \DefineVerbatimEnvironment{Highlighting}{Verbatim}{breaklines,commandchars=\\\{\}}