project:
  type: default

title: "Comparing Econometric and Machine Learning Approaches to Forecasting Indiaâ€™s CPI Inflation: An Evaluation of ARIMAX and XGBoost Models"

format:
  pdf:
    figwidth: 12
    figheight: 6
    papersize: a4
    tbl-colwidths: auto
    tbl-cap-location: top
    tbl-slide-width: true
    geometry:
      - margin=15mm
    toc: true
    toc-depth: 3
    metadata:
      header-includes: |
        \usepackage{fvextra}
        \DefineVerbatimEnvironment{Highlighting}{Verbatim}{breaklines,commandchars=\\\{\}}